### ISSUE TITLE
little help

### ISSUE THREAD

**Issue by peubraw** [nextscript/TS3DNS-v.1.0#1]
First of all, ty for the script.

I'm having a little issue, after I give the folder Databases and includes CHMOD 0777, I go to index.php and push "Create NOW" but no Hosting folder is created, it just shows the same "Create NOW" button like nothing happens... 

Here is my url: http://teamspeak3free.host/tsdns/index.php

any tip of what could be causing this ?

**Comment by nextscript** [comment]
1. Give the Main folder also CHMOD 0777.
2. If this no help then edit the index.php and delete on line 72 "error_reporting(0);" too get a error report of your problem.
3. If you get a Error and you dont now how too fix this send me this here.

**Comment by peubraw** [comment]
tyvm for your time and reply... 

I gave the main folder 0777 permissions too but it didn't helped (had tried that already)
screenshots:
1. http://clip2net.com/s/3x5QLYI
2. http://c2n.me/3x5QDQt

I've deleted the line 72 (screenshot: http://clip2net.com/s/3x5Qbf3) but it doesnt give any errors, still the same: http://teamspeak3free.host/tsdns/index.php

**Comment by nextscript** [comment]
Edit the index.php and add on top of  " if($_GET["id"] == "panel"){ " this : 
error_reporting(E_ALL);

**Comment by peubraw** [comment]
Done, several errors now, check this out: http://teamspeak3free.host/tsdns/index.php

**Comment by nextscript** [comment]
ok i update the index.php and fix this errors

**Comment by peubraw** [comment]
tyvm, please let me know when its ready for testing!

appreciate your time.

**Comment by nextscript** [comment]
See if your server already has : php5-common libapache2-mod-php5 php5-cli php5-mysql php5-curl php5-gd sqlite3

**Comment by peubraw** [comment]
I'm using 1and1.com webhosting, gona have to ask than that...

**Comment by nextscript** [comment]
apt-get remove apache2.2-common
apt-get remove apache2-mpm-prefork
apt-get remove apache2-mpm-worker
apt-get install apache2
apt-get install apache2-common
