### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by anjeshshrestha** [nextscript/TS3DNS-v.1.0#2]
Hi, I was trying to set this up on my web server, then i encountered a problem. The config file was empty, I have no idea what to put in there. Please help :D

Also I am getting this http://prntscr.com/cijq3t i did follow all the readme setps

**Comment by nextscript** [comment]
**See if your server already has :** 
php5-common
php5-dev
libapache2-mod-php5 
php5-cli 
php5-curl 
php5-gd 
php5-sqlite
sqlite3

**Support:**
Headers_sent Support
Session Support

**php.ini on the server:**
expose_php = On
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.cookie_lifetime = 0
session.serialize_handler = php
session.auto_start = 0

extension=curl.so
extension=pdo.so
extension=pdo_sqlite.so
extension=sqlite.so
extension=mysqli.so
extension=mysql.so
extension=pdo_mysql.so
extension=gd.so
extension=pdo_pgsql.so
extension=pgsql.so
extension=php_sqlite.dll
extension=php_bz2.dll
extension=php_curl.dll
extension=php_dba.dll

**Comment by anjesh12** [comment]
I will test that out thank you

**Comment by anjesh12** [comment]
yup everything is installed

**Comment by nextscript** [comment]
than replace your php.ini with my file:
[Download php.ini](https://www.dropbox.com/s/82bm0s2y44h8kr3/php.zip?dl=0) 

Scan report:
[(Virustotal.com _0 / 68_)](https://www.virustotal.com/de/url/15caa682bd4e1cb83a873e07e3e7e6022c37e5ca7b61fe0492e4becfa2789961/analysis/1474198212/)
